// PLAIN STRING METHOD

// 1 length
const sentence ="She codes conference is on again";
console.log(sentence.length);
console.log("\n")

// 2 toLowerCase
const name ="BENITA";
console.log(name.toLowerCase());
console.log("\n")

// 3 toUpperCase
const thing ="chair";
console.log(thing.toUpperCase());
console.log("\n")

// 3 slice
const words ="Every good boy deserves favour";
console.log(words.slice("24","31"));
console.log("\n")

// 4 replace
const  statement ="All carmel eat grass";
console.log(statement.replace("carmel","cow"));
console.log("\n")

// 5 replaceAll
const fullsentence ="Viola is a very interesting instrument. viola is part of the wooden family and viola also has a calming sound and pitch.";
console.log(fullsentence.replaceAll("viola","violin"));
console.log("\n")

// 6 split
const all ="Javascript is programmimg language";
console.log(all.split(""))
console.log("\n")
console.log(all.split(","))
console.log("\n")
console.log(all.split("/"))
console.log("\n")

// 7 valueOf
const message ="Javascript is a powerful programming language";
console.log(message.valueOf());
console.log("\n")

// 8 indexOf and lastindexOf
const blu ="Javascript is a scripting language";
console.log(blu.indexOf("a"));
console.log("\n")
console.log(blu.lastIndexOf("i"));
console.log("\n")

// 9 trim, trimStart and trimEnd
const clean =" Enharmonic equivalent "
console.log(clean.trim())
console.log("\n");
console.log(clean.trimStart());
console.log("\n");
console.log(clean.trimStart());